'use strict';

/**
 * @ngdoc function
 * @name prototipoApp.controller:ArticulosCtrl
 * @description
 * # ArticulosCtrl
 * Controller of the prototipoApp
 */
angular.module('prototipoApp')
  .controller('ArticulosCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];

    $scope.posts = [
      {
        title: 'Alimentos buenos para la salud',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in scelerisque mi, maximus pellentesque ligula.'
      },
      {
        title : 'Alimentos buenos para la regulación intestinal',
        content : 'Sed quis posuere turpis. Mauris eu convallis turpis, ac iaculis purus. Integer elementum diam vitae diam interdum, eget sollicitudin turpis condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam semper lacinia sem at tincidunt. Praesent vulputate odio vel neque volutpat vehicula. In laoreet placerat nisl, non facilisis risus efficitur a. Mauris at efficitur nisi. Proin eget magna vel turpis suscipit semper.        In vitae ipsum at lorem imperdiet dignissim. Phasellus rhoncus lorem ut magna ornare volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut orci in nisi facilisis pellentesque id eget justo. Nullam eget erat lacinia, congue orci vel, ullamcorper arcu. Curabitur est risus, pulvinar sed finibus sit amet, efficitur ac lorem. Praesent ultricies, nisi id malesuada fringilla, purus mauris viverra dolor, ut tempor lectus felis ac neque. Sed eu quam egestas, viverra ante at, porttitor eros. Aliquam erat volutpat. Aliquam egestas diam a dolor pharetra sodales. Cras a augue nec tortor efficitur tincidunt id quis velit.Sed neque sapien, hendrerit ac pellentesque at, faucibus ut urna. Etiam vehicula, magna eget fringilla pulvinar, metus mi iaculis eros, quis varius ex enim id arcu. Aliquam suscipit mauris sit amet turpis dictum, eget elementum sapien mattis. Praesent bibendum dolor ut laoreet scelerisque. Phasellus sagittis vitae nisl vitae mollis. Mauris sodales ipsum elit, non interdum justo mattis vel. Ut id lacus nec eros posuere ultrices eget ultricies dui. Duis vehicula orci at rutrum congue. Integer mollis turpis ac ligula feugiat, a ultrices turpis vestibulum.Ut non tincidunt lacus. Proin eget metus et nisl semper vehicula in quis leo. Quisque a nunc lacus. Vivamus commodo massa a metus porttitor luctus. Donec at gravida dui. Aliquam erat volutpat. Etiam condimentum erat eu mi fermentum faucibus. Nulla tincidunt lectus sapien, at ultrices odio rutrum interdum. Morbi gravida ipsum elit, quis pharetra nibh ornare eu. Donec non erat vel eros imperdiet fermentum eu at nisi.Aliquam pretium, felis ut posuere iaculis, eros neque vestibulum leo, volutpat aliquet enim nibh ut nulla. Vivamus iaculis venenatis ornare. Fusce lobortis urna non arcu porttitor condimentum. Suspendisse potenti. Donec mollis mi ac ex varius efficitur. Praesent suscipit, tellus vitae condimentum semper, ante odio mattis urna, a condimentum ligula orci sit amet quam. Nam varius, justo elementum sollicitudin blandit, orci quam varius elit, ut pulvinar leo erat vel dolor. Nullam at turpis commodo nunc iaculis molestie.'
      },
      {
        title : 'La alimentación y la informática',
        content : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in scelerisque mi, maximus pellentesque ligula. Integer felis eros, posuere vehicula libero non, ullamcorper dictum dolor. Sed quis posuere turpis. Mauris eu convallis turpis, ac iaculis purus. Integer elementum diam vitae diam interdum, eget sollicitudin turpis condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam semper lacinia sem at tincidunt. Praesent vulputate odio vel neque volutpat vehicula. In laoreet placerat nisl, non facilisis risus efficitur a. Mauris at efficitur nisi. Proin eget magna vel turpis suscipit semper.        In vitae ipsum at lorem imperdiet dignissim. Phasellus rhoncus lorem ut magna ornare volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut orci in nisi facilisis pellentesque id eget justo. Nullam eget erat lacinia, congue orci vel, ullamcorper arcu. Curabitur est risus, pulvinar sed finibus sit amet, efficitur ac lorem. Praesent ultricies, nisi id malesuada fringilla, purus mauris viverra dolor, ut tempor lectus felis ac neque. Sed eu quam egestas, viverra ante at, porttitor eros. Aliquam erat volutpat. Aliquam egestas diam a dolor pharetra sodales. Cras a augue nec tortor efficitur tincidunt id quis velit.Sed neque sapien, hendrerit ac pellentesque at, faucibus ut urna. Etiam vehicula, magna eget fringilla pulvinar, metus mi iaculis eros, quis varius ex enim id arcu. Aliquam suscipit mauris sit amet turpis dictum, eget elementum sapien mattis. Praesent bibendum dolor ut laoreet scelerisque. Phasellus sagittis vitae nisl vitae mollis. Mauris sodales ipsum elit, non interdum justo mattis vel. Ut id lacus nec eros posuere ultrices eget ultricies dui. Duis vehicula orci at rutrum congue. Integer mollis turpis ac ligula feugiat, a ultrices turpis vestibulum.Ut non tincidunt lacus. Proin eget metus et nisl semper vehicula in quis leo. Quisque a nunc lacus. Vivamus commodo massa a metus porttitor luctus. Donec at gravida dui. Aliquam erat volutpat. Etiam condimentum erat eu mi fermentum faucibus. Nulla tincidunt lectus sapien, at ultrices odio rutrum interdum. Morbi gravida ipsum elit, quis pharetra nibh ornare eu. Donec non erat vel eros imperdiet fermentum eu at nisi.Aliquam pretium, felis ut posuere iaculis, eros neque vestibulum leo, volutpat aliquet enim nibh ut nulla. Vivamus iaculis venenatis ornare. Fusce lobortis urna non arcu porttitor condimentum. Suspendisse potenti. Donec mollis mi ac ex varius efficitur. Praesent suscipit, tellus vitae condimentum semper, ante odio mattis urna, a condimentum ligula orci sit amet quam. Nam varius, justo elementum sollicitudin blandit, orci quam varius elit, ut pulvinar leo erat vel dolor. Nullam at turpis commodo nunc iaculis molestie.'
      },
      {
        title : 'Alimentos para limitar los hidratos de carbono',
        content : 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu convallis turpis, ac iaculis purus. Integer elementum diam vitae diam interdum, eget sollicitudin turpis condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam semper lacinia sem at tincidunt. Praesent vulputate odio vel neque volutpat vehicula. In laoreet placerat nisl, non facilisis risus efficitur a. Mauris at efficitur nisi. Proin eget magna vel turpis suscipit semper.        In vitae ipsum at lorem imperdiet dignissim. Phasellus rhoncus lorem ut magna ornare volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut orci in nisi facilisis pellentesque id eget justo. Nullam eget erat lacinia, congue orci vel, ullamcorper arcu. Curabitur est risus, pulvinar sed finibus sit amet, efficitur ac lorem. Praesent ultricies, nisi id malesuada fringilla, purus mauris viverra dolor, ut tempor lectus felis ac neque. Sed eu quam egestas, viverra ante at, porttitor eros. Aliquam erat volutpat. Aliquam egestas diam a dolor pharetra sodales. Cras a augue nec tortor efficitur tincidunt id quis velit.Sed neque sapien, hendrerit ac pellentesque at, faucibus ut urna. Etiam vehicula, magna eget fringilla pulvinar, metus mi iaculis eros, quis varius ex enim id arcu. Aliquam suscipit mauris sit amet turpis dictum, eget elementum sapien mattis. Praesent bibendum dolor ut laoreet scelerisque. Phasellus sagittis vitae nisl vitae mollis. Mauris sodales ipsum elit, non interdum justo mattis vel. Ut id lacus nec eros posuere ultrices eget ultricies dui. Duis vehicula orci at rutrum congue. Integer mollis turpis ac ligula feugiat, a ultrices turpis vestibulum.Ut non tincidunt lacus. Proin eget metus et nisl semper vehicula in quis leo. Quisque a nunc lacus. Vivamus commodo massa a metus porttitor luctus. Donec at gravida dui. Aliquam erat volutpat. Etiam condimentum erat eu mi fermentum faucibus. Nulla tincidunt lectus sapien, at ultrices odio rutrum interdum. Morbi gravida ipsum elit, quis pharetra nibh ornare eu. Donec non erat vel eros imperdiet fermentum eu at nisi.Aliquam pretium, felis ut posuere iaculis, eros neque vestibulum leo, volutpat aliquet enim nibh ut nulla. Vivamus iaculis venenatis ornare. Fusce lobortis urna non arcu porttitor condimentum. Suspendisse potenti. Donec mollis mi ac ex varius efficitur. Praesent suscipit, tellus vitae condimentum semper, ante odio mattis urna, a condimentum ligula orci sit amet quam. Nam varius, justo elementum sollicitudin blandit, orci quam varius elit, ut pulvinar leo erat vel dolor. Nullam at turpis commodo nunc iaculis molestie.'
      }
    ];
  });
